internalName: liv_keyboard

locales:
  en:
    name: &bundleName "Liv Keyboards"
    description: "Mobile OS keyboards for the Liv language from the Divvun group at UiT."
  nb:
    name: "Liv tastatur"
    description: "Mobiltastatur for Liv fra Divvun-gruppa."

author: The Divvun Group, UiT Norgga 치rktala코 universitehta
email: feedback@divvun.no

copyright: (c) 2017 Divvun/Giellatekno/UiT
organisation: UiT Norgga 치rktala코 universitehta

layouts: [liv]

version: 1.0
build: 1

targets:
  android:
    packageId: no.uit.giella.keyboards.liv
    icon: images/liv-icon.pdf
    keyStore: /Users/brendan/git/softkbdgen/test.keystore
    keyAlias: liv_keyboard

  ios: &AppleID
    codeSignId: "iOS Development"
    provisioningProfileId: Test
    packageId: no.uit.giella.keyboards.liv
    bundleName: *bundleName
    icon: images/liv-icon.png
  osx:
    <<: *AppleID
    icon: images/liv-icon.png
    codeSignId: "my-test-installer"