locales:
  liv:
    name: Livonian Keyboards
    description: >-
      Mobile OS keyboards for the Livonian language from the Divvun group
      at UiT.
  en:
    name: Livonian Keyboards
    description: >-
      Mobile OS keyboards for the Livonian language from the Divvun group
      at UiT.
  nb:
    name: Livonian tastatur
    description: Mobiltastatur for Livonian fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: TESTING@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
