template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 17
template_sha = "346f129f994bbadaaf70e03a281aef7056527a21"

[replacements]
__UND2C__ = "liv"
__UNDEFINED__ = "Liv"
__UND__ = "liv"
